services:
  - type: web
    name: casa-selecta
    runtime: node
    buildCommand: npm install
    startCommand: npm run meta
    plan: free
    envVars:
      - key: META_TOKEN
        sync: false
      - key: META_PHONE_NUMBER_ID
        sync: false
      - key: META_WABA_ID
        sync: false
      - key: META_VERIFY_TOKEN
        value: whatsbot-verify-token-2026
      - key: META_DISPLAY_NUMBER
        sync: false
